### PR TITLE
Lra 777 lsa ride share system report of approved drivers

### PR DESCRIPTION
**Pull request by jocelynanderson**
Add approved_driver report type

Cleaned up IF statements for queries after the addition of the approved_driver report type

### CODE REVIEW

**Comment by britaumich** [comment]
@jocelynanderson I got this error running 'approved_drivers' report:

`PG::CardinalityViolation: ERROR: more than one row returned by a subquery used as an expression`

It looks like the error happened when a program has more than one manager, I am not sure. 
I edited the query in my last commit: [573b6a2](https://github.com/lsa-mis/lsa_ride_share/pull/358/commits/573b6a254fc8a313b964b6c99e722bd39880114e)
Please look at the code and rest it. Thank you!

**Comment by jocelynanderson** [comment]
@britaumich I had two managers in one program in one program but obviously something is going on, I will test - thank you!

Why did all the tables get renamed ("students" to "st", "managers" to "mgr") in the query? When I see "st" I think of "street," the renaming is making things less clear to me.

**Comment by britaumich** [comment]
I could not make the query work without renaming tables with AS aliases. I got the errors like this:
`ERROR: missing FROM-clause entry for table "program" LINE 9: JOIN students ON program.id = students.program_id`
After adding aliases the query worked. The aliases might be changed, of course.

I am not sure what exactly was the cause of the error with the original query.

**Comment by britaumich** [comment]
@jocelynanderson I like how you edited aliases in the query. I did not know (did not think about such an option) that you can use a table's real name as an alias. Especially when tables' names are simple. The query looks much more understandable now. I'll test it again later today when I have time.

**Comment by britaumich** [comment]
@jocelynanderson I rearranged reports fields moving driver_type after the program.title in [540bf83](https://github.com/lsa-mis/lsa_ride_share/pull/358/commits/540bf83ba5bb0321e3ff7d6e5ad407908795eaac)

If that's OK with you, I'll approve and merge the pull request.

**Comment by jocelynanderson** [comment]
@britaumich looks great to me! thanks!

**Review by britaumich — APPROVED** [review]

**Pull request merged**
