### PR TITLE
Lra 605 lsa ride share add validation to all fields in vehicle report

### PR DESCRIPTION
**Pull request by jocelynanderson**
Added validation to vehicle reports:

- Mileage (start and end) allows for only numbers
- Gas (start and end) allows for only numbers, numbers must be 0 - 100 (gas is a percentage of fuel available)

Includes previous validation:
- End mileage cannot be lower than start mileage

### CODE REVIEW

**Comment by britaumich** [comment]
@jocelynanderson 

1. I think it would be nice to check mileage in the vehiclereport_controlle.js too. The same way as you did for gas.
2. gas_start and gas_end are floats in the database, so they are displayed like '20.0' in the form. Is that OK?  If they're percentages the fields should be integers, aren't they?

**Comment by jocelynanderson** [comment]
Thank you! 

1. I have added validation for gas_start and gas_end in vehiclereport_controller.js.
2. gas_start and gas_end have been migrated to integers. 

In regards to the validation for gas_start and gas_end, the model error pops up but not the controller warning. So I do not know if I did this 100% correct.

**Comment by britaumich** [comment]
Oh, I did not read your comment. You didn't add mileage_error to the fors (a div to display the error). Check the Inspect
->console, you will see the error

**Comment by jocelynanderson** [comment]
Thanks! I forgot to add the target to controller - this is done and I moved tThe error message in the model. Message now shows in similar fashion to gas error.

**Comment by britaumich** [comment]
I added clearing the error message to the js controller. To test try to add gas and mileage wrong numbers, then fix only one of them. See this commit [7262b40](https://github.com/lsa-mis/lsa_ride_share/pull/92/commits/7262b405d2e333fbf52ee17e3a2ba53717b3a410)
If you agree please tel me know, and I'll merge the pull request.

**Review by britaumich — APPROVED** [review]

**Review by britaumich — APPROVED** [review]

**Pull request merged**
