### PR TITLE
LRA-557-lsa-ride-share-check-the-header-design

### PR DESCRIPTION
**Pull request by rsmoke**
The header has been redesigned to address responsiveness in mobile and desktop views. I removed the unused files that are not relevant any longer.

The hamburger bar has a stimulus component to open and close it.
The navigation drops downs are purely CSS

### CODE REVIEW

**Comment by britaumich** [comment]
@rsmoke How did you create the branch for this ticket (LRA-557-lsa-ride-share-check-the-header-design)?
Was it created from the current staging branch?
Please compare it with the staging server.
Look at the Reservation page. The design is different.
On the Vehicle Reports page list of displayed fields is old.

**Comment by rsmoke** [comment]
> @rsmoke How did you create the branch for this ticket (LRA-557-lsa-ride-share-check-the-header-design)? Was it created from the current staging branch? Please compare it with the staging server. Look at the Reservation page. The design is different. On the Vehicle Reports page list of displayed fields is old.

The branch was created a few weeks ago. The files that changed an are conflicting are listed above and here is my take in a nutshell:
1) app/views/layouts/_header.html.erb and app/views/layouts/_mobile_menu_dropdown.html.erb are totally replaced for use by the header.
2) there are some new classes I created to support the header design

I will merge the current staging branch to into this branch to resolve the conflicts up  front.

**Comment by rsmoke** [comment]
> @rsmoke The admins' link to set up unit preferences is missing in your header.
> Please check the staging server - it's the SuperAdmin link if you log in as yourself.
> For Unit admins that would be the link.
> the link is: http://localhost:3000/unit_preferences/unit_prefs
 @britaumich it is under Unit Options

**Comment by rsmoke** [comment]
I am sort flummoxed why this keeps changing. i believe i fixed it now ?!?!?!

**Comment by rsmoke** [comment]
After discussing the current header I asked Rita B to give me a listing of who should see what links. She is updating the JIRA ticket LRA-557. After updating the header links I will reopen this PR

**Review by britaumich — APPROVED** [review]

**Pull request merged**
